export {
  Dialog,
  DialogClose,
  DialogDescription,
  DialogRoot,
  DialogTitle,
  DialogTrigger,
  NYTE_DIALOG_DEFAULT_VARIANTS,
  NYTE_DIALOG_VARIANTS,
  dialogVariants,
  type DialogCloseProps,
  type DialogDescriptionProps,
  type DialogProps,
  type DialogRootProps,
  type DialogTitleProps,
  type DialogTriggerProps,
  type NyteDialogRole,
  type NyteDialogSize,
  type NyteDialogVariantsProps,
} from "./dialog";
